-- RIGHT JOINS
SELECT * FROM PESSOA p
RIGHT JOIN CONTATO c ON p.ID_PESSOA  = c.ID_PESSOA;

SELECT * FROM PESSOA p
RIGHT JOIN PESSOA_X_PESSOA_ENDERECO pxpe ON p.ID_PESSOA  = pxpe.ID_PESSOA
RIGHT JOIN ENDERECO_PESSOA ep ON pxpe.ID_ENDERECO = ep.ID_ENDERECO;

SELECT * FROM PESSOA p
RIGHT JOIN PESSOA_X_PESSOA_ENDERECO pxpe ON p.ID_PESSOA  = pxpe.ID_PESSOA
RIGHT JOIN ENDERECO_PESSOA ep ON pxpe.ID_ENDERECO = ep.ID_ENDERECO
RIGHT JOIN CONTATO c ON p.ID_PESSOA = c.ID_PESSOA;  

-- FULL JOINS

SELECT * FROM PESSOA p
FULL JOIN CONTATO c ON p.ID_PESSOA  = c.ID_PESSOA;

SELECT * FROM PESSOA p
FULL JOIN PESSOA_X_PESSOA_ENDERECO pxpe ON p.ID_PESSOA  = pxpe.ID_PESSOA
FULL JOIN ENDERECO_PESSOA ep ON pxpe.ID_ENDERECO = ep.ID_ENDERECO;

SELECT * FROM PESSOA p
FULL JOIN PESSOA_X_PESSOA_ENDERECO pxpe ON p.ID_PESSOA  = pxpe.ID_PESSOA
FULL JOIN ENDERECO_PESSOA ep ON pxpe.ID_ENDERECO = ep.ID_ENDERECO
FULL JOIN CONTATO c ON p.ID_PESSOA = c.ID_PESSOA;

-- Exists

SELECT ID_PESSOA , NOME
FROM VEM_SER.PESSOA p
WHERE EXISTS (
    SELECT 1
    FROM PESSOA_X_PESSOA_ENDERECO pxpe
    WHERE pxpe.ID_PESSOA  = p.ID_PESSOA  
);

-- Correção Union
SELECT ID_PESSOA AS ID, NOME
FROM VEM_SER.PESSOA p 
UNION
SELECT ID_ENDERECO AS id, LOGRADOURO
FROM VEM_SER.ENDERECO_PESSOA ep; 


-- Esse foi desafiador e não tenho certeza se fiz da maneira correta
-- Feedbacks serão bem-vindos :)
