-- RIGHT JOINS
SELECT * FROM PESSOA p
RIGHT JOIN CONTATO c ON p.ID_PESSOA  = c.ID_PESSOA;

SELECT * FROM PESSOA p
RIGHT JOIN PESSOA_X_PESSOA_ENDERECO pxpe ON p.ID_PESSOA  = pxpe.ID_PESSOA
RIGHT JOIN ENDERECO_PESSOA ep ON pxpe.ID_ENDERECO = ep.ID_ENDERECO;

SELECT * FROM PESSOA p
RIGHT JOIN PESSOA_X_PESSOA_ENDERECO pxpe ON p.ID_PESSOA  = pxpe.ID_PESSOA
RIGHT JOIN ENDERECO_PESSOA ep ON pxpe.ID_ENDERECO = ep.ID_ENDERECO
RIGHT JOIN CONTATO c ON p.ID_PESSOA = c.ID_PESSOA;  

-- FULL JOINS

SELECT * FROM PESSOA p
FULL JOIN CONTATO c ON p.ID_PESSOA  = c.ID_PESSOA;

SELECT * FROM PESSOA p
FULL JOIN PESSOA_X_PESSOA_ENDERECO pxpe ON p.ID_PESSOA  = pxpe.ID_PESSOA
FULL JOIN ENDERECO_PESSOA ep ON pxpe.ID_ENDERECO = ep.ID_ENDERECO;

SELECT * FROM PESSOA p
FULL JOIN PESSOA_X_PESSOA_ENDERECO pxpe ON p.ID_PESSOA  = pxpe.ID_PESSOA
FULL JOIN ENDERECO_PESSOA ep ON pxpe.ID_ENDERECO = ep.ID_ENDERECO
FULL JOIN CONTATO c ON p.ID_PESSOA = c.ID_PESSOA;

-- Exists

SELECT ID_PESSOA , NOME
FROM VEM_SER.PESSOA p
WHERE EXISTS (
    SELECT 1
    FROM PESSOA_X_PESSOA_ENDERECO pxpe
    WHERE pxpe.ID_PESSOA  = p.ID_PESSOA  
);

SELECT p.ID_PESSOA , p.NOME, e.ID_ENDERECO, e.LOGRADOURO 
FROM VEM_SER.PESSOA p
JOIN PESSOA_X_PESSOA_ENDERECO pxpe ON p.ID_PESSOA = pxpe.ID_PESSOA
JOIN VEM_SER.ENDERECO_PESSOA e ON pxpe.ID_ENDERECO = e.ID_ENDERECO
WHERE EXISTS (
    SELECT 1
    FROM PESSOA_X_PESSOA_ENDERECO pxpe2
    WHERE pxpe2.ID_PESSOA  = p.ID_PESSOA 
);

-- Esse foi desafiador e não tenho certeza se fiz da maneira correta
-- Feedbacks serão bem-vindos :)
